import Head from 'next/head'
import Header from "../components/Header"
import { Inter } from '@next/font/google'
import Community from '@/components/Community'
import Stat from '@/components/Stat'
import Guide from '@/components/Guide'
import Footer from '@/components/Footer'
import Banner from '@/components/Banner'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>Elon Giveaway</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header/>

    <main className='main'>
      <Banner/>
      <Community/>
      <Stat/>
      <Guide/>
    </main>

    <Footer/>
    </>
  )
}
